### ISSUE TITLE
Code re-org: configs

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/deepdisc#16] opened 2023-10-17 19:15 UTC
Create package for fetching a config. detectron2 has two modes to load a config: yaml and a lazy config (https://detectron2.readthedocs.io/en/latest/tutorials/lazyconfigs.html).

There are a couple of configs in the LINCC drive: https://drive.google.com/drive/folders/1jlNJClGnWuBPCKkzYetIrBtq3sOHdJy0

**Comment by jeremykubica** [comment] 2023-10-23 12:57
Un-assigning myself for now since I have not had cycles to look at this.

**Comment by grantmerz** [comment] 2023-10-23 17:59
For reference - many parts of the code- including the models, trainers, data loaders, and predictors - all rely on configs to be built.  There are 2 types on configs that detectron2 uses: .py "LazyConfigs" and Yacs .yml configs.  Right now the training/inference scripts load a default config and change parameters/add extra ones using input from the command line.  It would be nice for reproducibility to just have the user supply a config with tweaked parameters rather than using command line arguments.  However, scripts use both Lazy and Yacs configs, to build the model and dataloaders, respectively.  I think combining into one .py config would be the easiest.  In the default .py config, have a section for the "loader" parameters that go into the .yml dataloader config.

**Comment by grantmerz** [comment] 2023-10-31 15:28
Here are the relevant config parameters that go into building the dataloaders https://github.com/facebookresearch/detectron2/blob/898507047cf441a1e4be7a729270961c401c4354/detectron2/config/defaults.py#L111C1-L111C1

**Comment by OliviaLynn** [comment] 2023-11-17 15:38
#60 is merged; remaining tasks:
- [ ] Updating var names and docstrings where cfg_loader is used/remove cfg_loader where cfg is present in:
  - [ ] predictors.py
    - return_predictor_transformer
  - [ ] loaders.py
    - return_train_loader
    - return_test_loader
  - [ ] trainers.py
    - return_lazy_trainer
- [ ] Add config files for other two modnames mvitv2 and vitdet
- [ ] Actually implement this throughout the repo and remove at-that-point-irrelevant `solo_test_run_transformers.py`

**Comment by OliviaLynn** [comment] 2023-11-30 18:57
| File | Solo Version? | Notes |
| ---- | ------------- | ------ |
| test_run_transformers  |  **yes**  | only works for swin and mvitv2 (vitdet throws CUDA error on main/pre-config-change) |
| test_run_transformers_DC2  |  **yes** (but untested)  | original file throws: `AssertionError: Got an invalid category_id=1 for a dataset of 1 classes` |
| test_run_transformers_DC2_redshift  |  **yes** (but untested)  | original file throws: `AssertionError: Got an invalid category_id=1 for a dataset of 1 classes` |
| test_eval_model | **not yet** | none |
| test_eval_model_DC2 | no | `KeyError: 'filename'` |
| test_eval_model_DC2_redshift | no | `KeyError: 'filename'` |
| train_decam | no | `AssertionError: Got an invalid category_id=2 for a dataset of 2 classes` |
| train_decam_testmodel | no | `PermissionError: [Errno 13] Permission denied: '/home/g4merz/deblend/.../cascade_mask_rcnn_swin_b_in21k_50ep.py'` |
| train_hsc_primary | no |`TypeError: main() takes 3 positional arguments but 4 were given` |
| train_hsc_primary_transformers | **not yet** | `PermissionError: [Errno 13] Permission denied: '/home/g4merz/../cascade_mask_rcnn_swin_b_in21k_50ep.py'` |

**Comment by grantmerz** [comment] 2023-11-30 20:51
To clarify what we talked about, the test scripts we want to make sure work are test_run_transformers.py (no VitDet is ok) and test_run_transformers_DC2.py/test_run_transformers_DC2_redshift.py.  If I understand correctly, the error you get from running test_run_transformers_DC2.py is from the code reading in a dataset that isn't DC2 data.  The path is set is a command line argument [here](https://github.com/lincc-frameworks/deepdisc/blob/7c8ab456eec7c83fd3a2d1c0df6f3fe624fa264a/test_run_transformers_DC2.py#L184C12-L184C12) .  Those scripts should read in ./tests/deepdisc/test_data/dc2/single_test.json.  Same with test_run_transformers_DC2_redshift.py.  You might also have to set nc=1 in the command line args.  For Issue #17 I think we could possibly move the command line args to the solo configs.  That way the top level training scripts could be the same

**Comment by OliviaLynn** [comment] 2023-12-04 16:31
(Notes-to-self)
Running 
`python solo_run_scripts/solo_test_run_transformers_DC2.py --data-dir  "./tests/deepdisc/test_data/dc2/"`
(on branch) gives two sets of errors, both involving the dataloader and ending in 
`TypeError: 'DictMapper' object is not callable`

However, I get that when I run this in main as well
`python test_run_transformers_DC2.py --data-dir  "./tests/deepdisc/test_data/dc2/"`
(haven't tried adding nc, as this particular script doesn't use that)

Making a note here to look into this, but I think I'll check with someone today to see if they also encounter this, just in case I'm making some kind of silly mistake.

**Comment by OliviaLynn** [comment] 2023-12-15 21:47
PR #81 out now, which addresses the main demo in deepdisc. Pending demo updates in rail_deepdisc, this will be functionally completed.

(The only outstanding items would be demo_decam, which has become outdated; we are currently evaluating whether or not to continue maintenance)

**Comment by drewoldag** [comment] 2023-12-20 21:31
The demo notebook in rail_deepdisc has been updated. Closing this issue.

**Closed by drewoldag** 2023-12-20 21:31 UTC
